version: '3.8'

services:
  ##### FRONTEND (NodeJS React) #####
  frontend:
    container_name: jaeung-kim-is21-frontend
    tty: true
    restart: on-failure
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    networks:
      - jaeung-kim-is21-network
    ports:
      - 3030:3030
    volumes:
      - ./frontend/src:/app/src

  ##### BACKEND (NodeJS Express API) #####
  backend:
    container_name: jaeung-kim-is21-backend
    tty: true
    init: true # Properly handles running as PID 1 inside a container. Source: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
    restart: on-failure
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    networks:
      - jaeung-kim-is21-network
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    environment:
      - PORT=8008
      - FRONTEND_URL=http://localhost:3030
      - BACKEND_URL=http://localhost:3000
    depends_on:
      - mongo
    ##### MONGODB #####
  mongo:
    container_name: jaeung-kim-is21-mongo
    image: mongo:latest
    restart: on-failure
    networks:
      - jaeung-kim-is21-network
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

networks:
  jaeung-kim-is21-network:
    driver: bridge

volumes:
  mongo-data: